### ISSUE TITLE
Voeg de bat bestanden ook toe

### ISSUE THREAD

**Issue by BasToTheMax** [BlauweEboy/Quiz-game#1]
dan weten mensen dat het geen virus is!

**Comment by BlauweEboy** [comment]
Hey BasToTheMax,
Bedankt voor je issue.
Ik voeg de bat bestanden er liever niet aan toe omdat er dan in de code kan worden gekeken en mijn game makkelijk kan worden nagemaakt. Wel ga ik nog een video maken waarin ik het bestand zelf download om misverstanden te voorkomen.
Deze video zal hier geplaatst worden: https://www.youtube.com/channel/UCl2b3DqbVQTz2f_KR82hwyw

Hopelijk is dit begrijpbaar. Anders kun je me altijd nog op Discord bereiken :).

Ik hoop dat dit hielp.

Mvg Stan

**Comment by BasToTheMax** [comment]
Het doel van github is om je projecten te delen MET de code, zodat anderen die kunnen verbeteren. 

TIP: als je een nieuwe repo maakt, kies de MIT licentie

**Comment by BlauweEboy** [comment]
Hey BasToTheMax,
Bedankt voor je issue.
Ik zal de code in de setup zetten.
Ook bedankt voor je tip, ik zal kijken wat de licentie inhoudt en hem waarschijnlijk gebruiken.

Hopelijk is dit begrijpbaar. Anders kun je me altijd nog op Discord bereiken :).

Ik hoop dat dit hielp.

Mvg Stan

**Comment by BasToTheMax** [comment]
Hmmm. Close?
